Add pipeline for fetching and transforming submission portal entry
microbiomedata/nmdc-runtime pull request #247
Opened 2023-05-09 22:39 UTC by pkalita-lbl

2023-05-10 19:25 UTC, pkalita-lbl commented on nmdc_runtime/site/graphs.py
> +    database = nmdc_schema_database_from_metadata_submission(metadata_submission)
Rename with verbs

2023-05-10 19:26 UTC, dwinston commented on nmdc_runtime/site/graphs.py
> +    database = nmdc_schema_database_from_metadata_submission(metadata_submission)
nmdc_portal_metadata_submission -> fetch_portal_submission_by_id

2023-05-18 20:42 UTC, dwinston commented
@pkalita-lbl I'm getting a testing error (see below). I'm not sure what's going on.

```
                actual = translator.get_database()
>               assert actual == expected
E               AssertionError: assert Database(acti..._version=None) == Database(acti..._version=None)
E                 
E                 Omitting 24 identical items, use -vv to show
E                 Differing attributes:
E                 ['study_set']
E                 
E                 Drill down into differing attribute study_set:
E                   study_set: [Study(id='fake:d862c2e3-6b0a-42f7-827c-67ebc8d44df7', name='Seasonal activities of the phyllosphere microbiome of perennial crops', description='Understanding the interactions between plants and microorganisms can inform microbiome management to enhance crop productivity and resilience to stress. Here, we apply a genome-centric approach to identify ecologically important leaf microbiome members on replicated plots of field-grown switc...
E                 
E                 ...Full output truncated (4 lines hidden), use '-vv' to show

tests/test_data/test_submission_portal_translator.py:252: AssertionError

```

2023-05-18 20:44 UTC, dwinston commented
Perhaps it would help to convert the DBs to json? Perhaps pytest has native helpful json-diffing.

2023-05-18 21:02 UTC, pkalita-lbl commented
Sorry about that! Will get it fixed up momentarily.

2023-05-19 14:02 UTC, dwinston commented
I get another test failure now:

```
>           fetch_nmdc_portal_submission_by_id(
                op_context, "353d751f-cff0-4558-9051-25a87ba00d3f"
            )

tests/test_ops/test_data_api_ops.py:34: 
...
E           dagster._core.errors.DagsterInvalidConfigError: Error in config for op
E               Error 1: Missing required config entry "config" at the root. Sample config for missing entry: {'config': {'submission_id': '...'}}
```

It seems in `test_metadata_submission` you call `fetch_nmdc_portal_submission_by_id` directly with two positional args. I think you need to build the op context with the submission id config value before calling it.

2023-05-19 19:05 UTC, dwinston requested changes
Generally good. Nice job abstracting out a `RuntimeApiClient`. The main thing is to refactor `validate_metadata` to not be a leaf op in its job, but then I think it's good to merge.

2023-05-19 19:05 UTC, dwinston commented on nmdc_runtime/site/ops.py
> +    response.raise_for_status()
`response.raise_for_status()` is redundant now, as I added it to `RuntimeApiUserClient.request`. 🙂 Please remove here.

2023-05-19 19:05 UTC, dwinston commented on nmdc_runtime/site/ops.py
> +    response.raise_for_status()
`response.raise_for_status()` is redundant now, as I added it to `RuntimeApiUserClient.request`. 🙂 Please remove here.

2023-05-19 19:05 UTC, dwinston commented on nmdc_runtime/site/ops.py
> +    response.raise_for_status()
`response.raise_for_status()` is redundant now, as I added it to `RuntimeApiUserClient.request`. 🙂 Please remove here.

2023-05-19 19:05 UTC, dwinston commented on nmdc_runtime/site/ops.py
> +        response.raise_for_status()
`response.raise_for_status()` is redundant now, as I added it to `RuntimeApiUserClient.request`. 🙂 Please remove here.

2023-05-19 21:23 UTC, pkalita-lbl commented on nmdc_runtime/site/graphs.py
> +    validate_metadata(database)
Yeah that was intentional. My thought was that even in the event that the translated `nmdc:Database` does not validate you might want to see what the pipeline produced as a debugging artifact. Is that an abuse of the DRS store?

2023-05-24 16:03 UTC, dwinston commented on nmdc_runtime/site/graphs.py
> +    validate_metadata(database)
No. It could be a bit more explicit in the graph flow, but it's fine.

2023-05-24 16:04 UTC, merged