Update `get_data` notebook in runtime documentation to use napa style identifiers
microbiomedata/nmdc-runtime pull request #598
Opened 2024-07-17 18:34 UTC by PeopleMakeCulture

# Description

Updates documentation notebook to use napa style identifiers

Fixes user research issue [#34](https://github.com/microbiomedata/user_research/issues/34)

## Type of change

- [ ] Documentation update

# How Has This Been Tested?

All cells ran successfully on local jupyter server

**Configuration Details**: none

# Definition of Done (DoD) Checklist:
A simple checklist of necessary activities that add verifiable/demonstrable value to the product by asserting the quality of a feature, not the functionality of that feature; the latter should be stated as acceptance criteria in the issue this PR closes. Not all activities in the PR template will be applicable to each feature since the definition of done is intended to be a comprehensive checklist. Consciously decide the applicability of value-added activities on a feature-by-feature basis.

- [ ] My code follows the style guidelines of this project (have you run `black nmdc_runtime/`?)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (in `docs/` and in <https://github.com/microbiomedata/NMDC_documentation/>?)
- [ ] I have added tests that prove my fix is effective or that my feature works, incl. considering downstream usage (e.g. <https://github.com/microbiomedata/notebook_hackathons>) if applicable.
- [ ] New and existing unit and functional tests pass locally with my changes (`make up-test && make test-run`)

2024-07-17 22:47 UTC, aclum commented on docs/nb/get_data.ipynb
>        " 'mongo_filter_dict': {'description': {'$regex': 'GFF'}},\n",
```suggestion
      " 'mongo_filter_dict': {'data_object_type': {'$regex': 'GFF'}},\n",
```

2024-07-17 22:57 UTC, aclum commented on docs/nb/get_data.ipynb
> +    "id_biosample = \"igsn:IEWFS000A\" #UPDATE\n",
```suggestion
    "id_biosample = \"nmdc:bsm-11-mbnqn650\"\n",
```

2024-07-17 22:58 UTC, aclum commented on docs/nb/get_data.ipynb
> +    "id_biosample = \"igsn:IEWFS000A\" #UPDATE\n",
The new ID for igsn:IEWFS000A is nmdc:bsm-11-mbnqn650

2024-07-17 22:58 UTC, aclum requested changes
See individual comments.

2024-10-21 21:41 UTC, aclum commented on docs/nb/get_data.ipynb
> +      "\n"
@PeopleMakeCulture  can you remove this keyboard interruption text?

2024-10-21 21:41 UTC, aclum commented
@PeopleMakeCulture  do you have time to revisit this PR?

2025-07-29 03:23 UTC, eecavanna commented
I think this notebook has since been deleted from the repository.

TODO:
- [ ] Confirm whether it has been deleted. If it has, close this PR.

2025-07-29 03:25 UTC, closed without merging