Display copy-paste HTTP Authorization header with Bearer token on Swagger UI for ORCiD-Authenticated user
microbiomedata/nmdc-runtime pull request #812
Opened 2024-12-05 22:28 UTC by dwinston

closes #742

In this branch, I used the Swagger UI's `onComplete` parameter to display bearer token info if present as a cookie (e.g. via ORCiD login).

### Details

<img width="1203" alt="image" src="https://github.com/user-attachments/assets/254cf835-1975-4f25-83dd-7db403743d28">

### Related issue(s)

Closes #742
...

### Related subsystem(s)

- [x] Runtime API (except the Minter)
- [ ] Minter
- [ ] Dagster
- [ ] Project documentation (in the `docs` directory)
- [ ] Translators (metadata ingest pipelines)
- [ ] MongoDB migrations
- [ ] Other

### Testing

- [x] I tested these changes (explain below)
- [ ] I did not test these changes

I tested these changes by manual inspection of `http://127.0.0.1:8000/docs`

### Documentation

- [x] I **have not checked** for relevant documentation yet (e.g. in the `docs` directory)
- [ ] I have **updated** all relevant documentation so it will remain accurate
- [ ] Other (explain below)

### Maintainability

- [x] I used `black` to format all the Python files I created/modified
- [x] The PR title is in the imperative mood (e.g. "Do X") and not the declarative mood (e.g. "Does X" or "Did X")

2024-12-06 18:48 UTC, shreddd commented
I think this is a reasonable solution. In the interest of security best practice can add a display toggle that will turn this on/off on the user's screen?

2024-12-06 21:22 UTC, eecavanna commented
Hi @dwinston, @shreddd and I looked at this branch together during today's hackathon (and we both got it up and running locally). I will take a shot at implementing the `***` masking that @shreddd described. I'll post another message here when I'm done (whether I succeeded or failed—the potential hurdle being understanding how the JS-in-PY gets transformed between the Python context and the final web page, and at what point the HTML-in-JS elements eventually get mounted to the DOM).

2024-12-06 22:14 UTC, shreddd requested changes
Add a show hide/toggle similar to https://data.microbiomedata.org/user
<img width="1232" alt="Screen Shot 2024-12-06 at 2 14 10 PM" src="https://github.com/user-attachments/assets/891df458-35ee-49ef-b357-5d6062324de3">

2024-12-06 22:39 UTC, eecavanna commented
Hi @shreddd, here's what I have added:

The token is masked by default:

![image](https://github.com/user-attachments/assets/badb4463-36f9-4441-92f5-2c457d92a9ac)

When the user clicks "Show token", it gets unmasked (I've blurred it in my screenshot tool):

![image](https://github.com/user-attachments/assets/a67429b6-d6b3-4eb3-890a-95ac07cbdefd)

When the user clicks "Copy token," the token (intentionally not the entire header) gets copied to their clipboard and a success message appears. If their browser doesn't support copying, an error message will appear instead.

![image](https://github.com/user-attachments/assets/b5c8f452-4fd3-4098-91d6-4bb5e7a1b6e1)

What do you think?

2024-12-06 22:56 UTC, eecavanna commented on nmdc_runtime/api/main.py
> +            </head>""",
I didn't realize this snippet was added as part of this same PR. I will remove the unnecessary trailing backslashes now.

2024-12-06 23:03 UTC, eecavanna commented
OK, I'm done working on this PR (I have closed `nmdc-runtime` in my IDE, shut down my Docker Compose stack, and am going to context switch to another task).

2024-12-06 23:08 UTC, eecavanna approved these changes
I validated the functionality locally.

If I hadn't just posted a message saying I was going to switch context, I think I would take a few minutes to convert `<double-quote>` into literal single quote characters, and also revisit whether those trailing backslashes are necessary in all the places they currently exist (given that they were not necessary in the second argument to `.replace()`). If this gnaws at me, I'll come back and do that stuff (I think it'll facilitate future maintenance). Either way, I'm comfortable with this being merge din as is.

2024-12-06 23:58 UTC, eecavanna commented
OK, I'm done addressing what I wanted to on this branch. I'm comfortable with this being merges in as is, assuming @shreddd is comfortable with the masking/copying behavior. I'm going to shift my focus away from this PR now.

2024-12-07 00:02 UTC, eecavanna approved these changes

2024-12-07 00:05 UTC, eecavanna commented
I'll merge this in now. It:
- Displays the token
- Masks the token by default
- Allows the user to unmask the token (by clicking a button)
- Allows the user to copy the token to their clipboard (by clicking a button)
- Shows a message saying whether the copy operation was successful

Risks:
- Stakeholders are not satisfied with the masking behavior

I am comfortable with that risk, given the narrow scope of these changes and the fact that there's still a week until `main` will be released to production (in case any stakeholders want to roll this back).

2024-12-07 00:07 UTC, merged