696 update dagster op for materialize alldocs
microbiomedata/nmdc-runtime pull request #817
Opened 2024-12-06 22:25 UTC by mkshah605

In this branch, I updated materialize_alldocs in the dagster file.

### Details
In this PR, I:
- updated the "materialize_alldocs" in the dagster op to reflect functionality in bulk_validation_referential_integrity_check.ipynb 
- added necessary utils to utils.py
- replaced `pick` function to use `keyfilter` directly

### Related issue(s)
- Related to #696 

### Related subsystem(s)
- [X] Dagster
- [X] Project documentation (in the `docs` directory)

### Testing
- [X] I tested these changes (explain below)
- [ ] I did not test these changes

I tested these changes by making sure the `ensure_alldocs` job runs in my local dagster environment: ![Succesful Dagster Run](https://github.com/user-attachments/assets/68d11c9e-9ff6-4731-8c27-55903d8bc01b) 

### Documentation
- [ ] I **have not checked** for relevant documentation yet (e.g. in the `docs` directory)
- [X] I have **updated** all relevant documentation so it will remain accurate

### Maintainability
- [X] Every Python function I defined includes a docstring _(test functions are exempt from this)_
- [X] Every Python function parameter I introduced includes a type hint (e.g. `study_id: str`)
- [X] All "to do" or "fix me" Python comments I added begin with either `# TODO` or `# FIXME`
- [X] I used `black` to format all the Python files I created/modified
- [X] The PR title is in the imperative mood (e.g. "Do X") and not the declarative mood (e.g. "Does X" or "Did X")

2024-12-13 15:52 UTC, PeopleMakeCulture requested changes

2024-12-13 15:52 UTC, PeopleMakeCulture commented on nmdc_runtime/site/ops.py
> +            new_doc["_type_and_ancestors"] = schema_view.class_ancestors(doc_type)
Test needs to be updated to expect `_type_and_ancestors` as the array of class ancestors

2024-12-13 18:33 UTC, merged

2024-12-13 18:58 UTC, eecavanna commented
Hi @mkshah605, thanks for implementing this.

I have a question about something in the diff (CC: @dwinston):

```py
            slots_to_include = ["id", "type"] + document_reference_ranged_slots[
                doc_type
            ]
            new_doc = keyfilter(lambda slot: slot in slots_to_include, doc)
            new_doc["_type_and_ancestors"] = schema_view.class_ancestors(doc_type)
```

Will the documents in the `alldocs` collection populated via this algorithm have all of the fields they have in the upstream, source-of-truth collections; or will they only have the fields `id`, `type`, `_type_and_ancestors`, and any fields that the schema says can contain references to documents?

2024-12-13 19:02 UTC, dwinston commented
> Hi @mkshah605, thanks for implementing this.
> 
> I have a question about something in the diff (CC: @dwinston):
> 
> ```python
>             slots_to_include = ["id", "type"] + document_reference_ranged_slots[
>                 doc_type
>             ]
>             new_doc = keyfilter(lambda slot: slot in slots_to_include, doc)
>             new_doc["_type_and_ancestors"] = schema_view.class_ancestors(doc_type)
> ```
> 
> Will the documents in the `alldocs` collection populated via this algorithm have all of the fields they have in the upstream, source-of-truth collections; or will they only have the fields `id`, `type`, `_type_and_ancestors`, and any fields that the schema says can contain references to documents?

The latter. I verified that the current direct usage of `alldocs` in the API only seeks document-reference-containing fields.

2024-12-19 00:30 UTC, shreddd commented
@dwinston - we should be careful when changing fields in all-docs since other parts of the API depend on it. Let's do a sanity check during one if the sync or squad meetings if there is a potentially breaking change to all-docs format or interface.

2024-12-19 11:31 UTC, dwinston commented
Gotcha. I'm glad we have a sanity-checking "happy path" automated test for `GET /data_objects/study/{study_id}` incoming via <https://github.com/microbiomedata/nmdc-runtime/issues/725>.